name: ALInvite
version: ${project.version}
main: com.alinvite.ALInvite
api-version: '1.20'
author: Allen_Linong
description: 邀请新玩家入服的激励系统插件
folia-supported: true
softdepend: [PlaceholderAPI, LuckPerms, Vault, PlayerPoints]
website: https://github.com/AllenLinong/ALInvite
load: STARTUP

commands:
  alinvite:
    description: ALInvite 主命令
    usage: /<command> [args]
    aliases: [ali, invite]
    permission: alinvite.use

permissions:
  alinvite.use:
    description: 允许使用主命令和查看菜单
    default: true
  alinvite.buygift:
    description: 允许购买礼包
    default: true
  alinvite.veteran:
    description: 允许生成邀请码并成为传火者
    default: false
  alinvite.rebate:
    description: 允许获得充值返点
    default: false
  alinvite.contribution:
    description: 允许使用贡献返点
    default: false
  alinvite.admin:
    description: 管理员权限
    default: op
